### ISSUE TITLE
fix: null values in equity report

### ISSUE THREAD

**Issue by vanhoofmaarten** [isaaceindhoven/dependency-health-monitor#36] opened 2022-06-16 09:33 UTC
When calculating the equity report of the package `nuxt-mq`, the equity report returns NaN and null values.

```json
"equityReport": {
    "difference": null,
    "severity": "Extremely inequitable",
    "explanation": "nuxt-mq has 9394 weekly downloads and is therefore expected to have a minimum financial health score of undefined. nuxt-mq's financial health score is 0. The difference between the ideal and the current is NaN and is therefore seen as Extremely inequitable."
},
```

Because of these values, this package is scored as extremely inequitable, while it seems that it should be fairly equitable, seen the usage.

**Comment by Ensar025** [comment] 2022-06-16 14:26
Thank you for the bug report!

The cause for the error is found. When calculating the equity score, we take the closest log of 10 rounded down, in nuxt-mq's case, that is 1000. That value (1000) is then used in the [equity scale](https://github.com/isaaceindhoven/dependency-health-monitor/blob/f8f38409e599c64a53e802892d4c4050e55d0f7d/packages/equity-score-calculator/src/constants.ts#L1) to determine the minimum financial health score. Because the equity scale does not have a value for 1000, it returns 0.

The error is fixed by making the minimum possible log of 10 100k instead of any possible value.

Resolved in 20900e8a336e48e790c16abc49efadd31d102ffb

**Closed** 2022-06-17 12:59 UTC
Labels: bug
